### ISSUE TITLE
导入数据报错

### ISSUE THREAD

**Issue by ohblue** [zhanghan1990/zipline-chinese#1]
```
(zipline_env) ❯ python mongodb.py
Traceback (most recent call last):
  File "mongodb.py", line 305, in <module>
    l.insert_zipline_treasure_format()
  File "mongodb.py", line 240, in insert_zipline_treasure_format
    self.treasure['treasure'].drop()
AttributeError: LoadDataCVS instance has no attribute 'treasure'
```

**Comment by fenggui321** [comment]
@ohblue  mongodb.py文件里面conn函数在main被注释了。你打开去掉main部分注释就好了。

**Comment by liujinhao1988** [comment]
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "/home/liujinhao/zipline-chinese/zipline/data/mongodb.py", line 301, in <module>
    l.insert_zipline_treasure_format()
  File "/home/liujinhao/zipline-chinese/zipline/data/mongodb.py", line 240, in insert_zipline_treasure_format
    self.treasure['treasure'].drop()
AttributeError: 'LoadDataCVS' object has no attribute 'treasure'

去掉了也不行
